---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- devtools/
- app/tests/
- lib/