from .aws_describe_instances import rules as rules_aws_describe_instances
from .aws_describe_load_balancers import rules as rules_aws_describe_load_balancers
from .aws_describe_volumes import rules as rules_aws_describe_volumes
from .aws_list_buckets import rules as rules_aws_list_buckets
from .aws_describe_images import rules as rules_aws_describe_images

from .aws_describe_vpcs import rules as rules_aws_describe_vpcs
from .aws_describe_subnets import rules as rules_aws_describe_subnets
from .aws_describe_vpc_peering_connections import rules as rules_aws_describe_vpc_peering_connections


from .aws_describe_vpn_gateways import rules as rules_aws_describe_vpn_gateways
from .aws_describe_vpc_endpoints import rules as rules_aws_describe_vpc_endpoints
from .aws_describe_route_tables import rules as rules_aws_describe_route_tables
from .aws_describe_network_interfaces import rules as rules_aws_describe_network_interfaces
from .aws_describe_nat_gateways import rules as rules_aws_describe_nat_gateways
from .aws_describe_network_acls import rules as rules_aws_describe_network_acls
from .aws_describe_security_groups import rules as rules_aws_describe_security_groups
from .aws_describe_snapshots import rules as rules_aws_describe_snapshots
from .aws_describe_cdns import rules as rules_describe_cdns
from .aws_describe_db_list import rules as rules_describe_db_list
from .aws_describe_autoscaling_group import rules as rules_describe_autoscaling_group
from .aws_describe_scaling_plans import rules as rules_aws_describe_scaling_plans
from .aws_describe_cdns_rtmp import rules as rules_aws_describe_cdns_rtmp

from .aws_list_functions import rules as rules_aws_list_functions
from .aws_list_layers import rules as rules_aws_list_layers
from .aws_list_queues import rules as rules_list_queues
from .aws_describe_cache_clusters import rules as rules_describe_cache_clusters
from .aws_list_identities import rules as rules_list_identities
from .aws_describe_domains import rules as rules_describe_domains
from .aws_list_tables import rules as rules_list_tables
from .aws_get_rest_apis import rules as rules_get_rest_apis
from .aws_get_apis import rules as rules_get_apis