def rules(conn):
    return {
        'unique_id': {'call': 'switch', 'source': 'NetworkInterfaceId'},
        'association': {'call': 'switch', 'source': 'Association'},
        'attachment': {'call': 'switch', 'source': 'Attachment'},
        'availability_zone': {'call': 'switch', 'source': 'AvailabilityZone'},
        'description': {'call': 'switch', 'source': 'Description'},
        'groups': {'call': 'switch', 'source': 'Groups'},
        'interface_type': {'call': 'switch', 'source': 'InterfaceType'},
        'ipv6_addresses': {'call': 'switch', 'source': 'Ipv6Addresses'},
        'mac_address': {'call': 'switch', 'source': 'MacAddress'},
        'private_dns_name': {'call': 'switch', 'source': 'PrivateDnsName'},
        'private_ip_address': {'call': 'switch', 'source': 'PrivateIpAddress'},
        'private_ip_addresses': {'call': 'switch', 'source': 'PrivateIpAddresses'},
        'requester_id': {'call': 'switch', 'source': 'RequesterId'},
        'requester_managed': {'call': 'switch', 'source': 'RequesterManaged'},
        'source_dest_check': {'call': 'switch', 'source': 'SourceDestCheck'},
        'subnet_id': {'call': 'switch', 'source': 'SubnetId'},
        'vpc_id': {'call': 'switch', 'source': 'VpcId'},
        'family': {'call': 'setV', 'source': 'NetworkInterfaces'},
        'datacenters': {'call': 'fctDcApp',
                        'source': {**conn}},
        'environment': {'call': 'arrCatcher',
                        'source': {'field': 'Tags', 'sKey': 'Key', 's': 'environment', 'catcher': 'Value'}},
        'status': {'call': 'switch', 'source': 'State'},
        'tags': {'call': 'fctTags', 'source': 'Tags'},
        'active': {'call': 'switchOptions',
                   'source': {'field': 'State',
                              'options': {'detaching': False, 'invalid': False},
                              'default': True
                              }},
        'owner': {'call': 'fctOwner',
                  'source': {**conn}},
        'roles': {'call': 'fctRoles',
                  'source': {**conn}}
    }